### ISSUE TITLE
Error: Cannot read properties of null (reading 'login')

### ISSUE THREAD

**Issue by vivekjivani** [RocketChat/Rocket.Chat.GitHub.Action.Notification#10]
Seeing this weird error randomly, I am using the RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1

below is the sample snippet about how I am using this github action
```

 name: 🔔✅ Send success notification to RocketChat
  if: success()
  uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
  with:
    type: "success"
    job_name: "🤖📦🚀 Build & deploy Success"
    URL: <ROCKETCHAT_WEBHOOK>
    commit: true
    token: <GITHUB_TOKEN>
```
