### ISSUE TITLE
##[error]Request failed with status code 400

### ISSUE THREAD

**Issue by sayjeyhi** [RocketChat/Rocket.Chat.GitHub.Action.Notification#2]
I did tried this action but we are getting 400 status code .
```yaml
name: Rocket.Chat Notification

on:
  pull_request:
    types: [opened, review_requested, reopened, assigned]

jobs:
  send_message_on_rocket:
    runs-on: ubuntu-latest
    steps:
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Lint Check*'
          mention: 'here'
          mention_if: 'failure'
          channel: '#github-updates'
          username: 'github'
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
```
